spring.application.name=desafio-pagamento
# Configurações do Banco de Dados H2 embutido
spring.datasource.url=jdbc:h2:mem:pagamentosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar a consola do H2 no navegador para facilitar os  testes
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Formatar o JSON na resposta da API
spring.jackson.serialization.indent_output=true